version: '3'
services:
  api:
    container_name: api
    build:
      context: "./api"
    volumes:
      - ./api:/usr/app/
    command: ["npm", "run", "dev"]
    depends_on:
      - nats
    links:
      - nats
    environment:
      - NATS_URI=nats://nats:4222
    ports:
      - 3000:3000
  cart-service:
    container_name: cart-service
    build:
      context: "./cart-service"
    volumes:
      - ./cart-service:/usr/app/
    command: ["npm", "run", "dev"]
    depends_on:
      - nats
    links:
      - nats
    environment:
      - NATS_URI=nats://nats:4222

  products-service:
    container_name: products-service
    build:
      context: "./products-service"
    volumes:
      - ./products-service:/usr/app/
    command: ["npm", "run", "dev"]
    depends_on:
      - nats
    links:
      - nats
    environment:
      - NATS_URI=nats://nats:4222
  
  nats:
    container_name: nats
    image: nats:latest
    ports:
      - 4222:4222
      - 8222:8222
      - 6222:6222